/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    var numero = 9
    val algo = "arbol"
    println("Hay $numero")
    println("Hay $algo")
}
